"""Structured content for the ASTRA-66 package: parts, fasteners, electronics, interfaces,
tolerances, envelope, risks, OpenRocket inputs. Costs are USD planning ranges (ASSUMPTION;
prices vary by country and supplier) and exclude motors, tools and shipping."""
import analysis as A

X = A.X
f = lambda v: (f"{v:.1f}".rstrip("0").rstrip("."))
R_SH_D = A.BODY_ID - A.FIT_SH

# make: MAKE (fabricate) / BUY (purchase) / EXT (external certified component, never fabricated)
# ver: "both" = in low-cost and recommended build, "rec" = recommended build only
PARTS = [
    # ---------------------------------------------------------------- 100 NOSE
    dict(pn="NC-101", name="Nose tip section", mod="100", qty=1, mat="PETG (ASA if painted dark)", meth="FDM print standing on the spigot, tip up, 0.2 mm layers, 3 perimeters, 0 % infill",
         dims=f"Tangent ogive sta 0–{f(A.NC_SPLIT)}, wall {f(A.NC_WALL)}, solid tip {f(A.NC_TIP_SOLID)}; {f(A.NC_SPLIT_WEB)} mm split web + spigot {f(A.NC_SPIGOT_L)} × {f(A.NC_SPIGOT_WALL)} wall", tol="OD ±0.3; spigot fit tune on coupon",
         iface=f"Spigot into NC-102 socket, {f(A.FIT_SOCKET)} diametral (I-00)", assy="30-min epoxy, align seam, tape jig", make="MAKE", lo=2, hi=4, ver="both", purpose="Aerodynamic nose, low drag at M<0.3", mass="NC-101"),
    dict(pn="NC-102", name="Nose base + shoulder", mod="100", qty=1, mat="PETG", meth="FDM print split face down; chamfered lugs/bosses need no support; 4 perimeters in shoulder",
         dims=f"Ogive sta {f(A.NC_SPLIT)}–{f(A.NC_L)} + spigot socket; shoulder ⌀{f(R_SH_D)} × {f(A.NC_SH_L)}, wall {f(A.NC_SH_WALL)}; 3 radial M3 insert bosses @ {A.NC_SCREW_ANG}°; 3 lugs sta {f(A.X['sh_end'] - A.NC_BH_T - A.NC_LUG_L)}–{f(A.X['sh_end'] - A.NC_BH_T)} @ {A.NC_LUG_ANG}°", tol=f"Shoulder ⌀{f(R_SH_D)} +0/−0.15",
         iface="I-01: 3× M3 radial into PL-201 @ sta 294", assy="Heat-set inserts, then bond NC-101", make="MAKE", lo=3, hi=5, ver="both", purpose="Nose-to-payload interface", mass="NC-102"),
    dict(pn="NC-103", name="Nose bulkhead / ballast mount", mod="100", qty=1, mat="PETG", meth="FDM print flat, 60 % gyroid",
         dims=f"⌀{f(R_SH_D - 2 * A.NC_SH_WALL - 0.2)} × {f(A.NC_BH_T)}, ⌀{f(A.CLR_M6)} centre, 3× ⌀{f(A.CLR_M3)} @ R{f(R_SH_D / 2 - A.NC_SH_WALL - A.NC_LUG_T / 2)}", tol="Holes +0.2/−0", iface="3× M3 × 10 into NC-102 lug inserts", assy="Bolt; rod nut on aft face", make="MAKE", lo=0.5, hi=1, ver="both", purpose="Closes payload bay forward; carries ballast", mass="NC-103"),
    dict(pn="NC-104", name="Ballast rod kit", mod="100", qty=1, mat="A2 stainless M6 rod, nylock nuts, M6 fender washers", meth="Cut rod to 86 mm, deburr",
         dims=f"M6 × {f(A.BALLAST_ROD_L + 6)}", tol="Length ±1", iface="Through NC-103", assy="Stack washers as needed to hit target CG; nylock both ends", make="BUY", lo=3, hi=5, ver="both", purpose="Adjustable stability trim", mass="NC-104"),
    # ---------------------------------------------------------------- 200 PAYLOAD
    dict(pn="PL-201", name="Payload tube", mod="200", qty=1, mat="66 mm-class kraft/phenolic body tube", meth="Cut from stock with tube-cutting jig",
         dims=f"⌀{f(A.BODY_OD)}/⌀{f(A.BODY_ID)} × {f(A.PL_L)}; 3× ⌀3.4 @ sta 294; ⌀{f(A.CAM_LENS_HOLE)} lens hole @ sta {f(X['cam'])}/270°; 25 × 40 hatch cut-out @ sta {f(X['hatch'])}/90°", tol="Length ±0.5; end squareness ≤0.5",
         iface="I-01 nose, I-02 AV coupler bond", assy="Mark holes with printed wrap-around drill guide", make="MAKE", lo=6, hi=10, ver="both", purpose="Houses payload bay", mass="PL-201"),
    dict(pn="PL-202", name="GPS / sensor tray + bracket", mod="200", qty=1, mat="PETG", meth="FDM print", dims=f"{f(A.TRAY_W)} × {f(A.TRAY_L - A.TRAY_FOOT_T)} × {f(A.TRAY_T)} plate + 22 × 26 × {f(A.TRAY_FOOT_T)} foot ({f(A.TRAY_L)} overall); 2 M3 inserts @ (±{f(A.TRAY_HOLE_X)}, {f(A.TRAY_HOLE_Y)}); 6 M2.5 insert bosses", tol="—",
         iface="2× M3 × 16 from inside the AV bay through AV-303 into the foot inserts", assy="Modules on M2.5 standoffs", make="MAKE", lo=0.5, hi=1, ver="rec", purpose="GPS + optional sensor mount", mass="PL-202"),
    dict(pn="PL-203", name="Camera cradle", mod="200", qty=1, mat="PETG", meth="FDM print", dims="Pocket CAM_W × CAM_H × CAM_LEN (USER: measure camera); saddle R31.9", tol="Pocket +0.3/+0.1",
         iface="Bonded to tube wall, lens concentric with hole", assy="Dry-fit camera, epoxy saddle", make="MAKE", lo=0.5, hi=1, ver="rec", purpose="Holds onboard camera", mass="PL-203"),
    dict(pn="PL-204", name="Lens cowl", mod="200", qty=1, mat="ASA or PETG", meth="FDM print", dims="40 long × 20 wide × 8 high teardrop, 15° aft-looking window", tol="Saddle R33 ±0.2",
         iface="Bonded over lens hole", assy="Epoxy + fillet; sand fair", make="MAKE", lo=0.3, hi=0.5, ver="rec", purpose="Streamlines lens, protects on landing", mass="PL-204"),
    dict(pn="PL-205", name="Access hatch", mod="200", qty=1, mat="PETG", meth="FDM print curved panel (0.25 mm nozzle recommended: 1 mm wall)", dims=f"{f(A.HATCH_L - 2 * A.HATCH_GAP)} × {f(A.HATCH_W - 2 * A.HATCH_GAP)} on R33, 2× ⌀{f(A.CLR_M25)} @ ±{f(A.HATCH_SCREW_OFF)}", tol="Edge gap 0.3 ±0.15",
         iface="2× M2.5 × 6 button head into PL-206 ledge inserts", assy="Remove to reach camera button / GPS USB", make="MAKE", lo=0.3, hi=0.5, ver="rec", purpose="Service without removing nose", mass="PL-205/206"),
    dict(pn="PL-206", name="Hatch doubler frame", mod="200", qty=1, mat="PETG", meth="FDM print", dims=f"{f(A.FRAME_L)} × {f(A.FRAME_W)} saddle R{f(A.BODY_ID / 2 - 0.05)}, {f(A.FRAME_T)} thick; opening {f(A.HATCH_L - 12)} × {f(A.HATCH_W)} (6 mm ledges); 2 M2.5 insert bosses", tol="—",
         iface="Bonded inside tube around cut-out", assy="Epoxy before cutting final opening", make="MAKE", lo=0.3, hi=0.5, ver="rec", purpose="Restores tube stiffness at cut-out; carries the hatch", mass=None),
    # ---------------------------------------------------------------- 300 AVIONICS
    dict(pn="AV-301", name="Avionics coupler", mod="300", qty=1, mat="Commercial kraft/phenolic coupler", meth="Cut from stock",
         dims=f"⌀{f(A.CPL_OD)}/⌀{f(A.CPL_ID)} × {f(A.AV_CPL_L)}", tol="Slip fit in BODY_ID: 0.1–0.4 diametral", iface="I-02 bond (fwd 70), I-03 slip fit (aft 70)",
         assy="Bond fwd half into PL-201; aft half sanded / taped to tune separation force", make="BUY", lo=5, hi=8, ver="both", purpose="Avionics bay structure + separation joint", mass="AV-301"),
    dict(pn="AV-302", name="Switch band", mod="300", qty=1, mat="Body tube offcut", meth="Cut from stock", dims=f"⌀{f(A.BODY_OD)} × {f(A.AV_BAND_L)}; ⌀8 switch access @90°; 4× ⌀2 static ports @45°", tol="Length ±0.3",
         iface="Bonded centred on AV-301", assy="Bond with coupler inserted in both tubes (alignment)", make="MAKE", lo=0, hi=0, ver="both", purpose="Exterior band, switch and static-port access", mass="AV-302"),
    dict(pn="AV-303", name="Forward bulkhead", mod="300", qty=1, mat="6 mm birch ply ×2, laminated", meth="Laser cut or hole saw + disc-sander jig",
         dims=f"⌀{f(A.CPL_ID - 0.2)} + ⌀{f(A.CPL_OD)} discs; 2× M4 tee-nut ⌀{f(A.TNUT_BARREL_D)} @±{f(A.AV_ROD_SP / 2)} (flange fwd); ⌀{f(A.HARNESS_D)} harness @ y+{f(A.HARNESS_Y)}; 2× ⌀{f(A.CLR_M3)} @ (±{f(A.TRAY_HOLE_X)}, {f(A.TRAY_HOLE_Y)})", tol="Rod holes ±0.2 true position",
         iface="I-02; bears on coupler fwd end face", assy="Epoxy into coupler; seal with fillet", make="MAKE", lo=1, hi=2, ver="both", purpose="Rod anchor + payload/av separation", mass="AV-303"),
    dict(pn="AV-304", name="Aft bulkhead", mod="300", qty=1, mat="6 mm birch ply ×2, laminated", meth="Laser cut or hole saw",
         dims=f"As AV-303; 2× ⌀{f(A.CLR_M4)}; ⌀{f(A.CLR_M6)} eyebolt", tol="Rod holes ±0.2 true position", iface="I-04a recovery attachment; outer disc seats on AV-309",
         assy="Slides on rods; washer + nylock nut each rod", make="MAKE", lo=1, hi=2, ver="both", purpose="Removable service closure; shock-cord anchor", mass="AV-304"),
    dict(pn="AV-305", name="Threaded rods", mod="300", qty=2, mat="M4 A2-70 stainless", meth="Cut, deburr, chamfer", dims="M4 × 190", tol="±1", iface="AV-303 inserts ↔ AV-304 nuts",
         assy="Loctite 243 into inserts (metal-metal only)", make="BUY", lo=3, hi=5, ver="both", purpose="Clamp bay; carry recovery load to AV-303", mass="AV-305"),
    dict(pn="AV-306", name="Electronics sled", mod="300", qty=1, mat="PETG", meth="FDM print flat, 100 % around sleeves", dims=f"{f(A.SLED_W)} × {f(A.SLED_T)} × {f(A.SLED_L)}, 2 rod sleeves ⌀7.5/⌀4.4, 10 M2.5 insert bosses (25 mm pitch), switch tower {f(A.SW_TOWER_H)} high, 2 M3 cage inserts, zip slots", tol="Sleeve pitch 40 ±0.2",
         iface="Rides on AV-305", assy="Modules on M2.5 nylon standoffs", make="MAKE", lo=1, hi=2, ver="both", purpose="Modular electronics carrier", mass="AV-306"),
    dict(pn="AV-307", name="Arming switch", mod="300", qty=1, mat="COTS latching switch (screw or key type)", meth="Purchase", dims="Per maker; actuator reachable through ⌀8", tol="—",
         iface="Wired battery → regulator", assy="Mount to sled bracket aligned with band hole", make="BUY", lo=3, hi=8, ver="both", purpose="Power electronics on the pad only", mass=None),
    dict(pn="AV-308", name="Battery cage + strap", mod="300", qty=1, mat="PETG + hook-and-loop / aramid strap", meth="Print", dims=f"Open-bottom cage for {f(A.BAT_L)} × {f(A.BAT_W)} × {f(A.BAT_H)} cell (USER; width ≤ 28.8)", tol="—", iface="Sled underside, 2× M3 × 16 into AV-306 inserts", assy="Screw from below; strap through side slots", make="MAKE", lo=1, hi=2, ver="both", purpose="Positive battery retention under load", mass="AV-308"),
    dict(pn="AV-309", name="Aft bulkhead face gasket", mod="300", qty=1, mat="1.5 mm EVA / neoprene foam", meth="Knife/die cut from DXF", dims=f"Annulus ⌀{f(A.CPL_OD)} / ⌀{f(A.CPL_ID)}, 1.5 free ({f(A.GASKET_T)} compressed)", tol="—", iface="Coupler aft end face ↔ AV-304 outer disc", assy="Contact adhesive to AV-304 outer disc", make="MAKE", lo=1, hi=2, ver="both", purpose="Keeps ejection gas out of the bay", mass=None),
    dict(pn="AV-312", name="Rod spacers", mod="300", qty=4, mat="PETG", meth="FDM print upright", dims=f"⌀7.5 / ⌀4.4; 2 × {f(A.SLED_FWD_GAP)} fwd, 2 × {f(A.X['cpl_aft'] + A.GASKET_T - A.AV_BH_T - A.X['sled_aft'])} aft", tol="Length ±0.1",
         iface="On AV-305 between bulkheads and sled", assy="Fwd pair, sled, aft pair, then AV-304 + nuts", make="MAKE", lo=0.2, hi=0.5, ver="both", purpose="Clamps the sled axially", mass="AV-312"),
    dict(pn="AV-311", name="Forged eyebolt M6", mod="300", qty=1, mat="Forged steel, zinc or stainless", meth="Purchase", dims="M6 shank; RATED working load from maker", tol="—",
         iface="I-04a", assy="Nut + fender washer inside; threadlock", make="BUY", lo=3, hi=6, ver="both", purpose="Recovery attachment point", mass="AV-311"),
    # ---------------------------------------------------------------- 400 BOOSTER
    dict(pn="BO-401", name="Booster tube", mod="400", qty=1, mat="66 mm-class kraft/phenolic body tube", meth="Cut; slot with router jig or fine saw + file",
         dims=f"⌀{f(A.BODY_OD)}/⌀{f(A.BODY_ID)} × {f(A.BO_L)}; 4 slots {f(A.FIN_T + A.FIN_SLOT_CLR)} × {f(A.FIN_CR - A.FIN_TAB_FWD)} from the tab front, open aft; 2× ⌀{f(A.CLR_M4)} rail-button holes @{A.RB_ANG}°", tol="Slot width +0.2/−0; slots 90° ±0.5°",
         iface="I-03, I-06, I-07", assy="Mark slots with printed wrap guide", make="MAKE", lo=12, hi=20, ver="both", purpose="Recovery bay + fin can shell", mass="BO-401"),
    dict(pn="BO-402", name="Motor mount tube", mod="400", qty=1, mat="29 mm-class kraft/phenolic MMT", meth="Cut from stock",
         dims=f"⌀{f(A.MMT_OD)} OD; ID + length PER MOTOR/RETAINER MAKER (placeholder {f(A.MMT_L)})", tol="Axis parallel to body ≤0.3°",
         iface="I-05 (COTS retainer)", assy="Rings bonded while clamped in alignment jig", make="BUY", lo=4, hi=7, ver="both", purpose="Holds certified motor; transmits thrust", mass="BO-402"),
    dict(pn="BO-403", name="Fin-can core", mod="400", qty=1, mat="ASA (heat tolerance) — PETG only for ground demo", meth="FDM print aft-end down, rails 100 %, rings 70 %",
         dims=f"⌀{f(R_SH_D)} × {f(X['core_aft'] - X['core_fwd'])}; bore ⌀{f(A.MMT_OD + A.FIT_SH)}; 8 rails {f(A.CORE_RAIL_T)} thick; guide {f(A.FIN_T + A.FIN_GUIDE_CLR)}; tab floors to R{f(A.R_TAB_FLOOR)}; 4× M3 inserts @R{f(A.LOCK_SCREW_R)}; rail boss @{A.RB_ANG}°", tol="Guide width ±0.1; angular 90° ±0.3°",
         iface="I-06 fins; bonded to MMT + tube", assy="Bond to MMT, then slide into tube with fins as alignment keys", make="MAKE", lo=3, hi=5, ver="both", purpose="Locates and supports removable fins", mass="BO-403"),
    dict(pn="BO-404", name="Forward centering ring", mod="400", qty=1, mat="6 mm birch ply", meth="Laser cut / hole saw",
         dims=f"⌀{f(R_SH_D)} / ⌀{f(A.MMT_OD + A.FIT_SH)} × {f(A.CR_T)}; 6 × 3 aramid notch @225°", tol="OD +0/−0.2", iface="I-04b recovery load path",
         assy="Bond + fillets both faces", make="MAKE", lo=1, hi=2, ver="both", purpose="Centres MMT; shock-cord anchor ring", mass="BO-404"),
    dict(pn="BO-405", name="Aft fin lock ring", mod="400", qty=1, mat="6 mm birch ply (sealed)", meth="Laser cut", dims=f"⌀{f(R_SH_D)} / ⌀{f(A.RET_CLEAR_D)} [RET_CLEAR_D] × {f(A.LOCK_T)}; 4× ⌀3.4 @R26", tol="Bore per retainer +1",
         iface="4× M3 × 12 into BO-403", assy="Removable: unscrew to slide fins out aft", make="MAKE", lo=0.5, hi=1, ver="both", purpose="Axially locks fins", mass="BO-405"),
    dict(pn="BO-406", name="Fins", mod="400", qty=A.FIN_N, mat="3 mm aircraft birch ply (baseline) / 3.2 mm G10 (upgrade)", meth="Laser cut or scroll saw from 1:1 template; edges radiused",
         dims=f"Root {f(A.FIN_CR)}, tip {f(A.FIN_CT)}, span {f(A.FIN_S)}, sweep {f(A.FIN_XR)}; tab {f(A.FIN_TAB_L)} × {f(A.FIN_TAB_H)}", tol="Profile ±0.3; cant 0° ±0.25°",
         iface="I-06", assy="Slide in from aft, lock with BO-405; no glue", make="MAKE", lo=6, hi=12, ver="both", purpose="Stability; replaceable after damage", mass="BO-406"),
    dict(pn="BO-407", name="Motor retainer", mod="400", qty=1, mat="COTS 29 mm screw-on retainer (metal)", meth="PURCHASE — never fabricate", dims="All dimensions from manufacturer drawing", tol="Per manufacturer",
         iface="I-05", assy="Bond to MMT exactly per maker's instructions; mentor inspection", make="BUY", lo=20, hi=35, ver="both", purpose="Positive motor retention", mass="BO-407"),
    dict(pn="BO-408", name="Rail buttons", mod="400", qty=2, mat="COTS 1010-size rail buttons + screws", meth="Purchase", dims="Per maker; must match RANGE rail", tol="In line ±0.5 over 230 mm",
         iface="I-07", assy="Fwd into BO-409 insert, aft into BO-403 boss", make="BUY", lo=4, hi=8, ver="both", purpose="Launch guidance", mass="BO-408/409"),
    dict(pn="BO-409", name="Forward rail-button boss", mod="400", qty=1, mat="PETG", meth="FDM print", dims="20 × 16 × 8 saddle, insert per button screw", tol="—", iface="Bonded to tube + BO-404 fwd face", assy="Epoxy; install insert before bonding", make="MAKE", lo=0.2, hi=0.5, ver="both", purpose="Hard-point for rail button", mass=None),
    dict(pn="BO-410", name="Aramid anchor leader", mod="400", qty=1, mat="COTS flame-resistant aramid cord, rated", meth="Purchase; cut 1.5 m", dims="Rated breaking strength ≥ design (see loads)", tol="—",
         iface="I-04b", assy="Wrap MMT between BO-404 and BO-403, bond with epoxy, exit through notch", make="BUY", lo=6, hi=10, ver="both", purpose="Heat-proof recovery anchor", mass="BO-410"),
    # ---------------------------------------------------------------- 500 RECOVERY
    dict(pn="RC-501", name="Parachute", mod="500", qty=1, mat="Ripstop nylon", meth="PURCHASE", dims=f"Nominal ⌀≈{f(A.CHUTE_D)} (42 in class)", tol="—", iface="Quick link to shock cord loop at 1/3 from AV end",
         assy="Z-fold per maker; lines untangled", make="BUY", lo=25, hi=45, ver="both", purpose="Descent ≈ 5 m/s", mass="RC-501"),
    dict(pn="RC-502", name="Parachute protector", mod="500", qty=1, mat="Flame-resistant fabric (e.g. Nomex-type)", meth="PURCHASE", dims="Size per maker for chute + 64 mm tube", tol="—", iface="Between chute and motor ejection gas", assy="Burrito wrap", make="BUY", lo=10, hi=18, ver="both", purpose="Protects chute from ejection heat", mass="RC-502"),
    dict(pn="RC-503", name="Shock cord", mod="500", qty=1, mat="Tubular nylon, rated", meth="PURCHASE", dims="4 m, sewn end loops", tol="—", iface="AV-311 ↔ BO-410 via RC-504", assy="Accordion fold, masking-tape bundles", make="BUY", lo=8, hi=15, ver="both", purpose="Energy absorption, keeps parts tethered", mass="RC-503"),
    dict(pn="RC-504", name="Quick links", mod="500", qty=3, mat="Steel, marked working load", meth="PURCHASE", dims="4–5 mm; rated WLL ≥ design", tol="—", iface="Recovery train", assy="Screw gate closed, check", make="BUY", lo=4, hi=8, ver="both", purpose="Serviceable connections", mass="RC-504/505"),
    dict(pn="RC-505", name="Swivel", mod="500", qty=1, mat="Ball-bearing swivel, rated", meth="PURCHASE", dims="Rated ≥ design", tol="—", iface="Chute riser", assy="Between chute and cord", make="BUY", lo=3, hi=6, ver="rec", purpose="Prevents line twist", mass=None),
    # ---------------------------------------------------------------- 600 EXTERNAL
    dict(pn="MT-601", name="Certified motor", mod="600", qty=1, mat="EXTERNAL — certified commercial product", meth="Purchased by / through a certified mentor or club; not designed, modified or stored by students unless the law and the club allow",
         dims="From certification data", tol="—", iface="I-05", assy="Prepared & installed per maker instructions under mentor/RSO supervision", make="EXT", lo=0, hi=0, ver="both", purpose="Propulsion + ejection", mass="MT-601"),
    dict(pn="MT-602", name="Igniter", mod="600", qty=1, mat="EXTERNAL — supplied / approved by maker, handled by range", meth="Not fabricated", dims="—", tol="—", iface="Range launch controller", assy="Installed at the pad only, per range procedure", make="EXT", lo=0, hi=0, ver="both", purpose="Ignition", mass=None),
    # ---------------------------------------------------------------- 700 GSE
    dict(pn="GS-701", name="Fin alignment jig", mod="700", qty=1, mat="PETG", meth="FDM print", dims="Collar ⌀82 × 30, 4 slots FIN_T+0.3", tol="Slots 90° ±0.2°", iface="Over booster tail", assy="Use during core bonding", make="MAKE", lo=1, hi=2, ver="both", purpose="Guarantees fin spacing & zero cant", mass=None),
    dict(pn="GS-702", name="CG balance cradle", mod="700", qty=1, mat="Ply offcuts + printed V-blocks", meth="Cut / print", dims="Knife-edge on 300 mm base", tol="—", iface="Supports airframe", assy="Balance fully loaded rocket, mark CG", make="MAKE", lo=1, hi=3, ver="both", purpose="Measure CG", mass=None),
    dict(pn="GS-703", name="Bench harness", mod="700", qty=1, mat="JST-XH/GH leads, USB extension", meth="Crimp", dims="—", tol="—", iface="I-08 connectors", assy="—", make="MAKE", lo=4, hi=8, ver="both", purpose="Ground test without airframe", mass=None),
    dict(pn="GS-704", name="Rail fit gauge", mod="700", qty=1, mat="300 mm offcut of 1010 rail (or range-lent)", meth="Purchase / borrow", dims="—", tol="—", iface="I-07", assy="Slide test, no binding", make="BUY", lo=0, hi=8, ver="rec", purpose="Verify button alignment", mass=None),
    dict(pn="GS-705", name="Display / transport stand", mod="700", qty=1, mat="12 mm ply", meth="Cut", dims="2 cradles, 600 apart", tol="—", iface="—", assy="—", make="MAKE", lo=3, hi=6, ver="rec", purpose="Exhibition + safe transport", mass=None),
]

ELECTRONICS = [
    dict(mod="Microcontroller", ex="RP2040 (e.g. Raspberry Pi Pico) or ESP32-S3 dev board", fn="Sensor fusion, state machine, logging", bus="—", loc="AV sled", lo=5, hi=15, ver="both"),
    dict(mod="IMU", ex="6-axis, ±32 g accel class (e.g. ST LSM6DSO32 breakout)", fn="Acceleration, rotation rate, liftoff detect", bus="I²C / SPI", loc="AV sled, hard-mounted near axis", lo=10, hi=18, ver="both"),
    dict(mod="Barometer", ex="Bosch BMP390 or TE MS5611 breakout", fn="Pressure altitude, apogee detect", bus="I²C", loc="AV sled, foam cover vs. light/draughts", lo=8, hi=15, ver="both"),
    dict(mod="Temperature", ex="TI TMP117 breakout or baro internal sensor", fn="Bay temperature log", bus="I²C", loc="AV sled / probe through band", lo=0, hi=10, ver="rec"),
    dict(mod="Data logging", ex="microSD SPI breakout + industrial / high-endurance card", fn="Primary data store", bus="SPI", loc="AV sled; card retained with tape", lo=5, hi=15, ver="both"),
    dict(mod="GPS", ex="u-blox M8/M9/M10-class module + patch antenna", fn="Position for recovery, ground track", bus="UART", loc="Payload bay tray (I-08)", lo=12, hi=45, ver="rec"),
    dict(mod="Telemetry radio (×2)", ex="Semtech SX127x LoRa module pair — ONLY on a band/power legal in your country", fn="Downlink to ground station", bus="SPI", loc="AV sled; antenna along band, away from GPS", lo=15, hi=40, ver="rec"),
    dict(mod="Battery", ex="1S LiPo with protection circuit, JST-PH", fn="Power (>2 h pad hold, measure)", bus="—", loc="AV-308 cage", lo=6, hi=12, ver="both"),
    dict(mod="Regulator", ex="3.3 V LDO or buck (≥500 mA)", fn="Clean rail", bus="—", loc="AV sled", lo=2, hi=6, ver="both"),
    dict(mod="Buzzer + LED", ex="Active piezo buzzer, status LED", fn="State annunciation, locate on ground", bus="GPIO", loc="AV sled", lo=2, hi=4, ver="both"),
    dict(mod="Separation sense", ex="Breakwire loop across I-03 (thin enamel wire + 2-pin connector)", fn="Detects deployment (logging only)", bus="GPIO input", loc="Band → booster", lo=1, hi=2, ver="both"),
    dict(mod="Camera", ex="Mini action / FPV-style recorder with own battery (USER choice)", fn="Onboard video", bus="Standalone", loc="PL-203 cradle", lo=25, hi=80, ver="rec"),
    dict(mod="Ground station", ex="2nd LoRa module + MCU + USB to laptop (Python logger)", fn="Live telemetry display", bus="USB serial", loc="Ground", lo=0, hi=0, ver="rec"),
]

FASTENERS = [
    ("M3 × 8 button head, A2", 3, "ISO 7380", "NC-102 ↔ PL-201 (I-01)"),
    ("M3 × 10 socket head, A2", 3, "ISO 4762", "NC-103 → NC-102 lugs"),
    ("M3 × 12 socket head, A2", 4, "ISO 4762", "BO-405 → BO-403"),
    ("M3 brass heat-set insert, L≈5", 14, "maker spec", "NC-102 (6), BO-403 (4), PL-202 foot (2), AV-306 (2)"),
    ("M3 × 16 socket head, A2", 2, "ISO 4762", "AV-303 → PL-202 foot (from inside the AV bay)"),
    ("M3 × 16 socket head, A2", 2, "ISO 4762", "AV-308 → AV-306 (from below)"),
    ("M2.5 × 6 button head, A2", 2, "ISO 7380", "PL-205 hatch → PL-206 ledges"),
    ("M2.5 brass heat-set insert", 19, "maker spec", "PL-206 (2), PL-202 (6), AV-306 grid (10) + switch tower (1)"),
    ("M2.5 nylon standoffs + screws kit", 1, "—", "Electronics modules"),
    ("M4 threaded rod A2-70, 190 mm", 2, "DIN 976", "AV-305"),
    ("M4 threaded insert / tee-nut", 2, "maker spec", "AV-303"),
    ("M4 nylock wing nut or nylock + washer", 2, "DIN 985 / DIN 315", "AV-304"),
    ("M4 insert + rail-button screw", 2, "per button maker", "BO-408 / BO-409 / BO-403"),
    ("M6 forged eyebolt + M6 nylock + fender washer", 1, "rated", "AV-311"),
    ("M6 threaded rod A2, 86 mm + 2 nylock + washers", 1, "DIN 976 / 985", "NC-104"),
    ("Quick link, rated", 3, "marked WLL", "RC-504"),
    ("Cable ties 2.5 mm, grommet ⌀8", "kit", "—", "Harness"),
]

MATERIALS = [
    ("Kraft or phenolic body tube, 66 mm class", "2 lengths (≥ 900 mm total)", "PL-201, AV-302, BO-401", "Measure OD/ID; buy a matching coupler from the same supplier", 20, 35),
    ("Matching coupler tube", "≥ 200 mm", "AV-301", "Same supplier/series as body tube", 5, 8),
    ("29 mm-class motor mount tube", "≥ 300 mm", "BO-402", "Confirm fit with motor maker's casing dimensions", 4, 7),
    ("Aircraft birch plywood 3 mm (3-ply)", "300 × 300", "BO-406", "Aviation grade; flat, void-free", 8, 14),
    ("Birch plywood 6 mm", "300 × 300", "AV-303/304, BO-404/405", "Laser-cut service or hole saw", 6, 10),
    ("PETG filament", "≈ 0.35 kg", "Nose, payload parts, sled, jigs", "Dry before printing", 8, 12),
    ("ASA filament", "≈ 0.1 kg", "BO-403, PL-204", "Print enclosed; ventilate", 4, 8),
    ("Epoxy, 30-min structural + laminating", "2 kits", "All bonds, fillets, fin edge sealing", "Measure by weight; record batch", 15, 25),
    ("Primer, filler, paint, sandpaper", "—", "Finish", "Light coats — paint is mass aft", 15, 30),
    ("Foam, tape, grommets, zip ties", "—", "Gasket, fit tuning, harness", "—", 5, 8),
]

ICD = [
    ("I-00", "NC-101 ↔ NC-102", "Bonded spigot in socket collar", f"Spigot {f(A.NC_SPIGOT_L)} (+{f(A.NC_SPLIT_WEB)} web), wall {f(A.NC_SPIGOT_WALL)}; ⌀ = 2(r({f(A.NC_SPLIT)}) − wall) − 0.3", f"Slip fit {f(A.FIT_SOCKET)} diametral (+0.1/+0.3)", "Coupon print; seam flush ≤0.2"),
    ("I-01", "NC-102 ↔ PL-201", "3× M3 radial screws into heat-set inserts", f"Shoulder ⌀{f(R_SH_D)} × {f(A.NC_SH_L)}; screws @ sta 294, 90/210/330°", "Shoulder +0/−0.15; hole ⌀3.4", "Fit, no rock; screws flush"),
    ("I-02", "PL-201 ↔ AV-301", "Permanent epoxy bond", f"{f(A.AV_INS)} mm insertion", "0.1–0.4 diametral gap", "Glue-line visible full circle"),
    ("I-03", "AV-301 ↔ BO-401", "Friction slip fit — SEPARATION JOINT", f"{f(A.AV_INS)} mm insertion", "Tune to measured separation force range agreed with mentor", "Spring-scale pull test, 5 repeats"),
    ("I-04a", "AV-304 ↔ recovery train", "Forged M6 eyebolt + quick link", "Eye on axis, aft face", "WLL ≥ design shock load", "Static proof load (see test plan)"),
    ("I-04b", "BO-404/BO-410 ↔ recovery train", "Bonded aramid leader + quick link", "Leader wrapped on MMT, exits notch @225°", "Rated breaking strength ≥ design", "Static proof load"),
    ("I-05", "BO-402 ↔ certified motor", "COTS retainer", "MMT ID, MMT_L, MMT_AFT_EXT, RET_CLEAR_D", "ALL FROM MANUFACTURER DOCUMENTATION", "Mentor inspection with the actual motor hardware"),
    ("I-06", "BO-406 ↔ BO-403/BO-401", "Slide-in tab on tab floor, axial lock ring", f"Tab {f(A.FIN_TAB_L)} × {f(A.FIN_TAB_H)} (root clears retainer, R{f(A.R_TAB_FLOOR)} floor); guide {f(A.FIN_T + A.FIN_GUIDE_CLR)}; slot {f(A.FIN_T + A.FIN_SLOT_CLR)}", "Cant 0 ±0.25°; 90 ±0.5°", "Jig + digital angle gauge; wiggle test; slide-out with retainer fitted"),
    ("I-07", "BO-408 ↔ range rail", "Rail buttons (1010 assumed)", f"Buttons @ sta {f(X['rb_fwd'])} and {f(X['rb_aft'])}, 45°", "In line ±0.5", "Slide on rail gauge, no binding"),
    ("I-08", "Payload bay ↔ AV bay", "Harness through AV-303 grommet", "⌀8 hole; keyed JST-GH/XH connectors both sides", "Strain relief within 20 mm", "Pull test 10 N; continuity"),
]

TOLERANCES = [
    ("Tube cut length", "per part", "±0.5", "Tube-cutting jig, steel rule"),
    ("Tube end squareness", "90°", "≤0.5 mm across ⌀", "Square on flat plate"),
    ("Printed shoulder / ring OD", f"⌀{f(R_SH_D)}", "+0 / −0.15", "Calipers, 3 places; print a 10 mm coupon first"),
    ("Coupler slip fit", "BODY_ID − CPL_OD", "0.1–0.4 diametral", "Hand fit + pull-force test"),
    ("Fin slot width (tube)", f"{f(A.FIN_T + A.FIN_SLOT_CLR)}", "+0.2 / −0", "Feeler / fin offcut"),
    ("Fin guide width (print)", f"{f(A.FIN_T + A.FIN_GUIDE_CLR)}", "±0.1", "Fin offcut slide test"),
    ("Fin angular spacing", "90°", "±0.5°", "GS-701 jig, protractor"),
    ("Fin cant", "0°", "±0.25°", "Digital angle gauge vs. tube datum"),
    ("Fin profile", "per drawing", "±0.3", "1:1 template overlay"),
    ("MMT concentricity", "on axis", "≤0.5 mm", "Measure ring-to-tube gap 4 places"),
    ("MMT parallelism", "on axis", "≤0.3°", "Straight rod through MMT vs. tube"),
    ("Rail-button line", "straight", "±0.5 over span", "Straight-edge / rail gauge"),
    ("Nose tip on axis", "on axis", "≤1.0 mm", "Roll on flat surface, watch tip"),
    ("AV rod pitch", f"{f(A.AV_ROD_SP)}", "±0.2", "Drill jig / laser cut"),
    ("Heat-set insert holes", "per insert maker", "per maker", "Test in coupon"),
]

ENVELOPE = [
    ("Liftoff mass", "≤ 1300 g design; must also satisfy local model-rocket limits", "ASM", "Scale, fully loaded"),
    ("Static margin at rail exit", "1.5 – 3.0 cal", "ASM (common practice)", "OpenRocket + measured CG"),
    ("Rail-exit velocity", "≥ 15 m/s (widely used guideline; follow range rule)", "ASM", "OpenRocket with RANGE rail length"),
    ("Max velocity", f"≤ {f(A.V_MAX)} m/s (M ≤ 0.27)", "ASM", "OpenRocket"),
    ("Max axial acceleration", f"≤ {f(A.N_AX)} g", "ASM", "OpenRocket; IMU range check"),
    ("Deployment velocity", "≤ 20 m/s at ejection (check delay options)", "ASM", "OpenRocket deployment-velocity output"),
    ("Descent rate", "4.5 – 6 m/s", "ASM", "OpenRocket; measured chute"),
    ("Ground wind", "≤ 15 km/h for this airframe (and within range limit)", "ASM", "Range anemometer"),
    ("Apogee", "Below field / airspace ceiling granted to the range", "USER", "Range RSO"),
    ("Airframe temperature", "No storage > 50 °C (PETG); inspect after sun exposure", "ASM", "Visual / fit check"),
]

RISKS = [
    ("Unstable flight", "CG aft of plan (tail-heavy build, heavier motor)", 5, 2, "Measure CG with motor installed; ballast via NC-104; OpenRocket with measured masses", "Swing/balance check + mentor sign-off"),
    ("Over-stable weathercocking", "High margin + low rail-exit speed in wind", 3, 3, "Margin ≤3 cal; rail-exit ≥15 m/s; launch only in low wind", "Simulation at 0/10/15 km/h wind"),
    ("Recovery failure", "Tight I-03 fit, tangled chute, wrong delay", 5, 2, "Measured separation force; packing procedure; delay chosen from sim by mentor", "Packing rehearsal, separation pull test"),
    ("Shock-cord / anchor failure", "Late/early deployment, heat damage", 4, 2, "Rated hardware ≥ design load; aramid near motor; protector", "Static proof load, post-flight inspection"),
    ("Motor retention failure", "Retainer bond or wrong hardware", 5, 1, "COTS retainer, installed per maker, inspected by mentor", "Pull test by hand + mentor inspection"),
    ("Printed part heat softening", "ASA/PETG near motor, hot car", 3, 3, "ASA core; ply lock ring; storage rule", "Post-flight fit check"),
    ("Fin loss / flutter", "Loose slide-in fit, damaged fin", 3, 2, "Lock ring, fit tolerance, flutter SF ≥ 2", "Wiggle test, inspect each flight"),
    ("Electronics brown-out / data loss", "Loose battery, vibration, cold", 2, 3, "Strapped battery, locking connectors, SD retention", "Shake test, pad-hold endurance test"),
    ("Radio non-compliance", "Wrong band / power", 3, 2, "Use only legally permitted ISM band and power", "Check national regulations"),
    ("Ground injury", "Incorrect motor handling, standing too close", 5, 1, "Only certified motors; mentor/RSO handles motor & igniter; safety code distances", "Range briefing, checklists"),
    ("Landing damage", "High descent rate, hard ground", 2, 3, "42 in class chute, fins recessed from tail, replaceable parts", "Post-flight inspection"),
]

OPENROCKET = [
    ("Nose cone", "Shape / shape parameter", "Ogive / 1.0 (tangent)", "ASM"),
    ("Nose cone", "Length · base ⌀ · wall", f"{f(A.NC_L)} mm · {f(A.BODY_OD)} mm · {f(A.NC_WALL)} mm", "ASM"),
    ("Nose cone", "Shoulder length · ⌀ · thickness", f"{f(A.NC_SH_L)} · {f(R_SH_D)} · {f(A.NC_SH_WALL)} mm", "ASM"),
    ("Nose cone", "Material / override mass", "PETG 1270 kg/m³ → then OVERRIDE with weighed mass", "USER"),
    ("Body tube 'Payload'", "Length · OD · ID", f"{f(A.PL_L)} · {f(A.BODY_OD)} · {f(A.BODY_ID)} mm", "ASM→USER"),
    ("Body tube 'Switch band'", "Length", f"{f(A.AV_BAND_L)} mm", "ASM"),
    ("Body tube 'Booster'", "Length", f"{f(A.BO_L)} mm", "ASM"),
    ("Inner tube 'AV coupler'", "Position · length · OD · ID", f"top of Switch band −{f(A.AV_INS)} · {f(A.AV_CPL_L)} · {f(A.CPL_OD)} · {f(A.CPL_ID)}", "ASM"),
    ("Bulkheads (in coupler)", "2 × 2 discs", f"6 mm ply at coupler ends (⌀{f(A.CPL_ID - 0.2)} / ⌀{f(A.CPL_OD)})", "ASM"),
    ("Inner tube 'MMT' (motor mount ON)", "Length · OD · ID · overhang", f"{f(A.MMT_L)} · {f(A.MMT_OD)} · from motor maker · {f(A.MMT_AFT_EXT)}", "COTS"),
    ("Centering rings", "Positions", f"top of MMT ({f(A.CR_T)} ply); core rings {f(A.CORE_RING_T)} mm at tab front and aft", "ASM"),
    ("Trapezoidal fin set", "Count · root · tip · height · sweep", f"{A.FIN_N} · {f(A.FIN_CR)} · {f(A.FIN_CT)} · {f(A.FIN_S)} · {f(A.FIN_XR)} mm", "ASM"),
    ("Trapezoidal fin set", "Thickness · cross-section · position", f"{f(A.FIN_T)} mm · Rounded · bottom of Booster, offset 0", "ASM"),
    ("Trapezoidal fin set", "Fin tabs", f"height {f(A.FIN_TAB_H)} · length {f(A.FIN_TAB_L)} · offset {f(A.FIN_TAB_FWD)} from root LE", "ASM"),
    ("Rail buttons", "Profile / position", "1010 class, 2 buttons, at CAD stations; angle 45°", "USER (range rail)"),
    ("Parachute", "Diameter · Cd · deploy", f"{f(A.CHUTE_D)} mm · {A.CHUTE_CD} (or maker value) · at ejection", "ASM"),
    ("Shock cord", "Length · material", "4 m tubular nylon (mass component OK)", "ASM"),
    ("Mass components", "Electronics, battery, camera, GPS, ballast", "Enter each at CAD station with WEIGHED mass", "USER"),
    ("Motor", "Motor configuration", "Select certified motor from built-in ThrustCurve database; set ejection delay option", "COTS"),
    ("Launch conditions", "Rail length · angle · wind · site altitude · temp", "From YOUR range; wind 0/10/15 km/h cases", "USER"),
    ("Simulation options", "Time step / geodetic", "Defaults; run ≥ 3 wind cases, Monte-Carlo optional", "ASM"),
]

TOOLS = [
    "FDM 3D printer (≥ 220 × 220 × 250 mm build volume), PETG + ASA capable (enclosure for ASA)",
    "Soldering iron with heat-set insert tips; digital calipers (0.01 mm)",
    "Fine-tooth saw or tube cutter + printed tube-cutting guide; hand files, sanding blocks",
    "Drill + brad-point bits; hole saw or laser-cutting service for ply parts",
    "Digital kitchen scale (0.1 g, 2 kg), spring/luggage scale for pull tests",
    "Digital angle gauge, square, straight-edge / aluminium angle",
    "Nitrile gloves, respirator for sanding and ASA printing, safety glasses",
    "Multimeter, USB-serial adapter, crimp tool for JST connectors",
]

BUILD_TIME = [
    ("CAD modelling, drawings, design review", "25–35 h"),
    ("Machine print time (all printed parts incl. jigs & coupons)", "30–40 h (unattended)"),
    ("Tube cutting, slotting, ply parts, dry fits", "12–18 h"),
    ("Bonding, fillets, cure (elapsed days)", "8–12 h work + 5–7 days"),
    ("Finishing: fill, prime, paint", "8–12 h + cure"),
    ("Electronics assembly and firmware", "30–60 h"),
    ("Ground testing and documentation", "12–20 h"),
    ("Total, part-time student pace", "≈ 8–12 weeks"),
]
