"""Build the ASTRA-66 engineering package: python build.py

Sources:  analysis/analysis.py, simulation/motor_config.json, documentation/generator/*
Outputs:  cad/astra66_params.scad, analysis/results/*, bom/*.csv, simulation/openrocket_inputs.csv,
          avionics/electronics.csv + avionics/diagrams/*.svg, documentation/drawings/*.svg,
          documentation/ASTRA-66_Engineering_Package.html
"""
import csv
import html
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "analysis"))
sys.path.insert(0, os.path.join(HERE, "documentation", "generator"))

import analysis as A  # noqa: E402
import data_tables as T  # noqa: E402
import drawings as D  # noqa: E402

DIAGRAMS = ("arch", "elec", "fsm")
TAGNAME = {"CALC": "CALCULATED", "ASM": "ASSUMPTION", "USER": "USER-SUPPLIED", "COTS": "COMMERCIAL SPEC"}


def esc(s):
    return html.escape(str(s))


def tag(t):
    key = t.split()[0].split("→")[0].split("(")[0].strip()
    cls = {"CALC": "calc", "ASM": "asm", "USER": "user", "COTS": "cots"}.get(key, "asm")
    label = TAGNAME.get(key, t)
    return f'<span class="tag t-{cls}">{esc(label)}</span>'


def tbl(headers, rows, cls="", num=(), raw=(), foot=None, caption=None):
    h = "".join(f'<th{" class=num" if i in num else ""}>{esc(x)}</th>' for i, x in enumerate(headers))
    body = []
    for r in rows:
        tds = []
        for i, c in enumerate(r):
            v = c if i in raw else esc(c)
            tds.append(f'<td{" class=num" if i in num else ""}>{v}</td>')
        body.append("<tr>" + "".join(tds) + "</tr>")
    ft = ""
    if foot:
        ft = "<tfoot><tr>" + "".join(f'<td{" class=num" if i in num else ""}>{c}</td>' for i, c in enumerate(foot)) + "</tr></tfoot>"
    cap = f"<caption>{esc(caption)}</caption>" if caption else ""
    return f'<div class="tw"><table class="{cls}">{cap}<thead><tr>{h}</tr></thead><tbody>{"".join(body)}</tbody>{ft}</table></div>'


def n(v, d=0):
    return f"{v:,.{d}f}"


def money(lo, hi):
    return f"${lo:,.0f}–{hi:,.0f}"


def main():
    R = A.run()
    X = A.X
    bw, ld, rec = R["bw"], R["loads"], R["recovery"]
    for d in ("cad", "analysis/results", "bom", "simulation", "avionics/diagrams", "documentation/drawings"):
        os.makedirs(os.path.join(HERE, d), exist_ok=True)

    # ------------------------------------------------------------------ OpenSCAD params
    lines = ["// ASTRA-66 parameters -- GENERATED by build.py from analysis.py. Edit analysis.py and rebuild,",
             "// or override here for quick CAD experiments (analysis will then be out of date).", ""]
    for p in A.P.values():
        if isinstance(p["v"], (int, float, list)):
            val = "[" + ", ".join(str(x) for x in p["v"]) + "]" if isinstance(p["v"], list) else p["v"]
            lines.append(f'{p["name"]:<16} = {val};   // [{TAGNAME[p["tag"]]}] {p["u"]} - {p["note"]}')
    params_path = os.path.join(HERE, "cad", "astra66_params.scad")
    new_params = "\n".join(lines) + "\n"
    old_params = open(params_path, encoding="utf-8").read() if os.path.exists(params_path) else None
    if new_params != old_params:          # keep the mtime when unchanged, so the CAD render cache stays valid
        open(params_path, "w", encoding="utf-8").write(new_params)

    # ------------------------------------------------------------------ CSV / JSON
    def wcsv(rel, header, rows):
        with open(os.path.join(HERE, *rel.split("/")), "w", newline="", encoding="utf-8") as fh:
            w = csv.writer(fh)
            w.writerow(header)
            w.writerows(rows)

    wcsv("analysis/results/parameters.csv", ["name", "value", "unit", "provenance", "note"],
         [[p["name"], p["v"], p["u"], TAGNAME[p["tag"]], p["note"]] for p in A.P.values()])
    wcsv("analysis/results/mass_budget.csv", ["id", "item", "module", "mass_g", "cg_station_mm", "provenance", "note"],
         [[i["id"], i["name"], i["module"], round(i["m"], 1), round(i["x"], 1), TAGNAME[i["tag"]], i["note"]] for i in R["items"]])
    wcsv("bom/bom.csv", ["part_no", "name", "module", "qty", "material", "method", "dimensions", "tolerance", "interface", "assembly",
                         "make_buy", "cost_usd_low", "cost_usd_high", "in_low_cost_build", "purpose"],
         [[p["pn"], p["name"], p["mod"], p["qty"], p["mat"], p["meth"], p["dims"], p["tol"], p["iface"], p["assy"], p["make"],
           p["lo"], p["hi"], p["ver"] == "both", p["purpose"]] for p in T.PARTS])
    wcsv("bom/fasteners.csv", ["fastener", "qty", "standard", "used_at"], [list(r) for r in T.FASTENERS])
    wcsv("bom/materials.csv", ["material", "quantity", "parts", "note", "cost_usd_low", "cost_usd_high"], [list(r) for r in T.MATERIALS])
    wcsv("avionics/electronics.csv", ["function", "example_class", "role", "bus", "location", "cost_usd_low", "cost_usd_high", "build"],
         [[e["mod"], e["ex"], e["fn"], e["bus"], e["loc"], e["lo"], e["hi"], e["ver"]] for e in T.ELECTRONICS])
    wcsv("simulation/openrocket_inputs.csv", ["component", "field", "value", "provenance"], [list(r) for r in T.OPENROCKET])
    summary = {k: R[k] for k in ("M0", "Mb", "Me", "cg0", "cgb", "cge", "sm0", "smb", "sme", "L", "LD")}
    summary.update(cp=bw["xcp"], loads=ld, recovery=rec, nose=R["nose"], trade=R["trade"], stations=X, motor_status=A.MOTOR_STATUS)
    json.dump(summary, open(os.path.join(HERE, "analysis", "results", "analysis.json"), "w"), indent=2, default=str)

    # ------------------------------------------------------------------ drawings
    sheets = D.all_sheets(R)
    S = {}
    for k, sh in sheets.items():
        svg = sh.render()
        S[k] = svg
        dest = ("avionics", "diagrams") if k in DIAGRAMS else ("documentation", "drawings")
        open(os.path.join(HERE, *dest, f"{k}.svg"), "w", encoding="utf-8").write(D.standalone(svg))

    # ------------------------------------------------------------------ values
    massmap = {i["id"]: i["m"] for i in R["items"]}
    low_parts = [p for p in T.PARTS if p["ver"] == "both"]
    consum = (50, 88)  # epoxy 15-25, paint/filler 15-30, fastener+insert kit 15-25, foam/tape 5-8
    el_low = [e for e in T.ELECTRONICS if e["ver"] == "both"]
    cost_low = (sum(p["lo"] for p in low_parts) + sum(e["lo"] for e in el_low) + consum[0],
                sum(p["hi"] for p in low_parts) + sum(e["hi"] for e in el_low) + consum[1])
    cost_rec = (sum(p["lo"] for p in T.PARTS) + sum(e["lo"] for e in T.ELECTRONICS) + consum[0],
                sum(p["hi"] for p in T.PARTS) + sum(e["hi"] for e in T.ELECTRONICS) + consum[1])
    sens = R["sens"]
    area, _ = A.fin_geom()
    import math
    V = dict(
        L=n(R["L"]), LD=n(R["LD"], 1), D=n(A.BODY_OD, 0), M0=n(R["M0"]), Mb=n(R["Mb"]), Me=n(R["Me"]),
        cg0=n(R["cg0"]), cgb=n(R["cgb"]), cge=n(R["cge"]), xcp=n(bw["xcp"]), sm0=n(R["sm0"], 2), smb=n(R["smb"], 2), sme=n(R["sme"], 2),
        cn_f=n(bw["cn_f"], 2), x_f=n(bw["x_f"]), x_nose=n(bw["x_nose"], 1), lf=n(bw["lf"], 1), kfb=n(bw["k_fb"], 3),
        rho_nose=n(R["nose"]["rho"], 1), tip_angle=n(R["nose"]["tip_half_angle"], 1), pay_bay=n(A.PAYLOAD_BAY_CLEAR), rec_bay=n(A.RECOVERY_BAY_L),
        tab_L=n(A.FIN_TAB_L), tab_H=n(A.FIN_TAB_H, 1), D_req=n(rec["D_req"] * 1000), v_sel=n(rec["v_sel"], 1),
        ke_sel=n([c for c in rec["chutes"] if c["D"] == int(A.CHUTE_D)][0]["ke"], 1), cord_L=n(rec["cord_L"]), md=n(rec["md"] * 1000),
        F_joint=n(ld["F_joint"]), F_thrust=n(ld["F_thrust"]), bond_area=n(ld["bond_area"]), bond_cap=n(ld["bond_cap"]), sf_bond=n(ld["sf_bond"], 1),
        F_rec=n(ld["F_rec_design"]), F_rec_req=n(2 * ld["F_rec_design"]), rod_cap=n(ld["rod_cap"]), sf_rod=n(ld["sf_rod"], 1), bh_sigma=n(ld["bh_sigma"], 1), sf_bh=n(ld["sf_bh"], 1),
        F_fin=n(ld["F_fin"], 1), M_root=n(ld["M_root"]), fin_sigma=n(ld["fin_sigma"], 2), sf_fin=n(ld["sf_fin"]), Vf=n(ld["Vf"]), sf_flutter=n(ld["sf_flutter"], 1),
        f1=n(ld["f1"]), AR=n(ld["AR"], 2), n_ax=n(A.N_AX), v_max=n(A.V_MAX), q=n(ld["q"]), m_upper=n(ld["m_upper"] * 1000),
        fin_le=n(X["fin_le"]), sm_at_max=n(sens[-1]["sm"], 2), m_sens_max=n(sens[-1]["motor_m"]), rb_span=n(X["rb_aft"] - X["rb_fwd"]),
        rb_fwd=n(X["rb_fwd"]), rb_aft=n(X["rb_aft"]), chute_D=n(A.CHUTE_D), sweep=n(math.degrees(math.atan(A.FIN_XR / A.FIN_S)), 1),
        fin_area=n(area), motor_m0=n(A.MOTOR_M0), motor_mb=n(A.MOTOR_MB), motor_L=n(A.MOTOR_L),
        cost_low=money(*cost_low), cost_rec=money(*cost_rec), n_parts=str(len(T.PARTS)), fin_S=n(A.FIN_S), fin_CR=n(A.FIN_CR), fin_CT=n(A.FIN_CT),
        fin_XR=n(A.FIN_XR), fin_T=n(A.FIN_T, 0), nc_L=n(A.NC_L), pl_L=n(A.PL_L), bo_L=n(A.BO_L), cpl_L=n(A.AV_CPL_L),
        mmt_L=n(A.MMT_L), mmt_fwd=n(X["mmt_fwd"]), ballast_note=n(sens[-1]["ballast"]),
        bh_mass=n(massmap["AV-303"]), nose_mass=n(R["modules"]["100 Nose"]["m"]),
        motor_status=A.MOTOR_STATUS,
        motor_flag=("<span class='tag t-asm'>PLACEHOLDER MOTOR</span> provisional until <code>simulation/motor_config.json</code> holds the selected certified motor's published data"
                    if A.MOTOR_STATUS == "PLACEHOLDER" else
                    f"<span class='tag t-cots'>MANUFACTURER DATA</span> {html.escape(str(A.MOTOR_CFG['motor']['designation']))}, verified {html.escape(str(A.MOTOR_CFG['verification']['date']))}"),
    )

    vr = os.path.join(HERE, "cad", "exports", "validation_results.json")
    if os.path.exists(vr):
        cv = json.load(open(vr, encoding="utf-8"))
        V.update(cad_rev=cv["cad_rev"], cad_date=cv["date"], cad_pass=str(cv["summary"]["PASS"]), cad_warn=str(cv["summary"]["WARN"]),
                 cad_fail=str(cv["summary"]["FAIL"]), cad_parts=str(len(cv["parts"])), cad_osc=cv["openscad"])
    else:
        V.update(cad_rev="B", cad_date="not run", cad_pass="—", cad_warn="—", cad_fail="—", cad_parts="—", cad_osc="OpenSCAD")

    # ------------------------------------------------------------------ tables
    TB = {}
    TB["params"] = tbl(["Parameter", "Value", "Unit", "Provenance", "Note"],
                       [[p["name"], p["v"], p["u"], tag(p["tag"]), p["note"]] for p in A.P.values()], "compact", num=(1,), raw=(3,))
    items = sorted(R["items"], key=lambda i: i["x"])
    TB["mass"] = tbl(["ID", "Item", "Module", "Mass g", "CG sta mm", "Moment g·m", "Provenance"],
                     [[i["id"], i["name"], i["module"], n(i["m"], 1), n(i["x"]), n(i["m"] * i["x"] / 1000, 1), tag(i["tag"])] for i in items],
                     "compact", num=(3, 4, 5), raw=(6,),
                     foot=["", "<b>Liftoff total</b>", "", f"<b>{n(R['M0'], 0)}</b>", f"<b>{n(R['cg0'])}</b>", f"<b>{n(R['M0'] * R['cg0'] / 1000, 1)}</b>", tag("CALC")])
    TB["modules"] = tbl(["Module", "Mass g", "CG sta mm", "Share"],
                        [[k, n(v["m"], 1), n(v["x"]), f"{v['m'] / R['M0'] * 100:.0f} %"] for k, v in R["modules"].items()], num=(1, 2, 3))
    TB["trade"] = tbl(["Option", "Fin area mm² (each)", "CNα fins /rad", "CP sta mm", "SM liftoff cal", "SM burnout cal", "Liftoff g"],
                      [[t["label"], n(t["area"]), n(t["cn_f"], 2), n(t["xcp"]), n(t["sm0"], 2), n(t["smb"], 2), n(t["M"])] for t in R["trade"]],
                      num=(1, 2, 3, 4, 5, 6))
    TB["chutes"] = tbl(["Nominal ⌀ mm", "Class", "Descent m/s", "Landing KE J"],
                       [[n(c["D"]), f'{c["inch"]} in', n(c["v"], 1), n(c["ke"], 1)] for c in rec["chutes"]], num=(0, 2, 3))
    TB["drift"] = tbl(["Apogee m", "Descent time s", "Drift @10 km/h m", "Drift @20 km/h m"],
                      [[n(d["apogee"]), n(d["t"]), n(d["w10"]), n(d["w20"])] for d in rec["drift"]], num=(0, 1, 2, 3))
    TB["shock"] = tbl(["Deployment speed m/s", "Est. peak load N", "Min. rated working load N (×2)"],
                      [[n(s_["v"]), n(s_["F"]), n(s_["req"])] for s_ in ld["shock"]], num=(0, 1, 2))
    sf_rows = [
        ["Recovery hardware (eyebolt, links, cord)", "Rated WLL ≥ 2 × est. load", f"≥ {V['F_rec_req']} N at 30 m/s case", "Choose from maker ratings", "ASM"],
        ["AV-305 rods (2 × M4 A2-70 proof)", "≥ 3", f"{V['rod_cap']} N vs {V['F_rec']} N → {V['sf_rod']}", "CALC", "CALC"],
        ["AV-304 bulkhead bending (12 mm ply)", "≥ 3", f"σ {V['bh_sigma']} MPa vs 40 → {V['sf_bh']}", "CALC from ASM allowables", "CALC"],
        ["MMT ring bonds, thrust transfer", "≥ 3", f"{V['bond_cap']} N vs {V['F_thrust']} N → {V['sf_bond']}", "CALC from ASM τ = 1 MPa", "CALC"],
        ["Fin root bending, 10° AoA at V_max", "≥ 3", f"σ {V['fin_sigma']} MPa → {V['sf_fin']}", "Landing loads govern — test", "CALC"],
        ["Fin flutter (screening)", "≥ 2 on velocity", f"V_f ≈ {V['Vf']} m/s vs {V['v_max']} → {V['sf_flutter']}", "Shear modulus ASM", "CALC"],
    ]
    TB["sf"] = tbl(["Item", "Required SF (ASM)", "Result", "Basis", "Tag"], [r[:4] + [tag(r[4])] for r in sf_rows], raw=(4,))
    mk = {"MAKE": '<span class="chip make">MAKE</span>', "BUY": '<span class="chip buy">BUY</span>', "EXT": '<span class="chip ext">EXTERNAL</span>'}
    TB["parts"] = tbl(["Part no.", "Name", "Qty", "Material", "Manufacturing", "Dimensions", "Tolerance", "Mass g", "Interface", "Assembly", "Make/Buy"],
                      [[p["pn"], p["name"], p["qty"], p["mat"], p["meth"], p["dims"], p["tol"],
                        (n(massmap[p["mass"]], 1) if p["mass"] in massmap else "—"), p["iface"], p["assy"], mk[p["make"]]] for p in T.PARTS],
                      "wide", num=(2, 7), raw=(10,))
    TB["bom"] = tbl(["Part", "Qty", "Material", "Manufacturing", "Est. cost (USD)", "Purpose", "Build"],
                    [[f'{p["pn"]} {p["name"]}', p["qty"], p["mat"], p["meth"].split(";")[0], ("—" if p["make"] == "EXT" else money(p["lo"], p["hi"])),
                      p["purpose"], "both" if p["ver"] == "both" else "recommended"] for p in T.PARTS], "compact", num=(1, 4))
    TB["fasteners"] = tbl(["Fastener", "Qty", "Standard", "Used at"], [list(r) for r in T.FASTENERS], "compact", num=(1,))
    TB["materials"] = tbl(["Material", "Quantity", "Parts", "Note"], [list(r[:4]) for r in T.MATERIALS], "compact")
    TB["electronics"] = tbl(["Function", "Example class (verify datasheet)", "Role", "Bus", "Location", "Est. USD", "Build"],
                            [[e["mod"], e["ex"], e["fn"], e["bus"], e["loc"], ("—" if e["hi"] == 0 else money(e["lo"], e["hi"])),
                              "both" if e["ver"] == "both" else "recommended"] for e in T.ELECTRONICS], "compact")
    TB["icd"] = tbl(["ID", "Between", "Type", "Key dimensions", "Tolerance", "Verification"], [list(r) for r in T.ICD], "compact")
    TB["tol"] = tbl(["Feature", "Nominal", "Tolerance", "Inspection method"], [list(r) for r in T.TOLERANCES], "compact")
    TB["envelope"] = tbl(["Parameter", "Recommended limit", "Basis", "Verified by"], [[a, b, tag(c), d] for a, b, c, d in T.ENVELOPE], raw=(2,))
    risk_rows = []
    for h_, c_, s_, l_, m_, v_ in T.RISKS:
        score = s_ * l_
        lvl = "high" if score >= 10 else "med" if score >= 6 else "low"
        risk_rows.append([h_, c_, str(s_), str(l_), f'<span class="risk r-{lvl}">{score} {lvl.upper()}</span>', m_, v_])
    TB["risks"] = tbl(["Hazard", "Cause", "S", "L", "Risk", "Mitigation", "Verification"], risk_rows, "compact", num=(2, 3), raw=(4,))
    TB["openrocket"] = tbl(["OpenRocket component", "Field", "Value to enter", "Source"], [[a, b, c, tag(d)] for a, b, c, d in T.OPENROCKET], "compact", raw=(3,))
    TB["tools"] = "<ul class='ticks'>" + "".join(f"<li>{esc(t_)}</li>" for t_ in T.TOOLS) + "</ul>"
    TB["buildtime"] = tbl(["Phase", "Estimate"], [list(r) for r in T.BUILD_TIME], "compact")
    buy = [p for p in T.PARTS if p["make"] in ("BUY", "EXT")]
    TB["buy"] = "<ul class='ticks'>" + "".join(f"<li><b>{esc(p['pn'])}</b> {esc(p['name'])} — {esc(p['mat'])}</li>" for p in buy) + "</ul>"
    mods = {}
    for p in T.PARTS:
        m_ = mods.setdefault(p["mod"], [0, 0, 0, 0])
        m_[0] += p["lo"]; m_[1] += p["hi"]
        if p["ver"] == "both":
            m_[2] += p["lo"]; m_[3] += p["hi"]
    modname = {"100": "100 Nose", "200": "200 Payload", "300": "300 Avionics structure", "400": "400 Booster", "500": "500 Recovery", "600": "600 Motor system (EXTERNAL)", "700": "700 Ground support"}
    crow = [[modname[k], money(v[2], v[3]), money(v[0], v[1])] for k, v in mods.items()]
    crow.append(["Electronics (see avionics table)", money(sum(e["lo"] for e in el_low), sum(e["hi"] for e in el_low)),
                 money(sum(e["lo"] for e in T.ELECTRONICS), sum(e["hi"] for e in T.ELECTRONICS))])
    crow.append(["Consumables: epoxy, paint, fastener & insert kit, foam", money(*consum), money(*consum)])
    TB["cost"] = tbl(["Group", "Low-cost build", "Recommended build"], crow, num=(1, 2),
                     foot=["<b>Total (excl. motors, tools, shipping)</b>", f"<b>{V['cost_low']}</b>", f"<b>{V['cost_rec']}</b>"])

    # ------------------------------------------------------------------ chart
    CH = chart(sens, R)

    # ------------------------------------------------------------------ assemble HTML
    tpl = ""
    for part in ("documentation/generator/template_a.html", "documentation/generator/template_b.html"):
        tpl += open(os.path.join(HERE, part), encoding="utf-8").read()
    missing = set()

    def sub(m):
        kind, key = m.group(1), m.group(2)
        src = {"V": V, "T": TB, "S": S}[kind]
        if key not in src:
            missing.add(f"{kind}:{key}")
            return f"[[{kind}:{key}]]"
        return src[key]
    out = re.sub(r"\{\{([VTS]):([A-Za-z0-9_]+)\}\}", sub, tpl).replace("{{CHART}}", CH)
    open(os.path.join(HERE, "documentation", "ASTRA-66_Engineering_Package.html"), "w", encoding="utf-8").write(out)
    print("built; missing placeholders:", sorted(missing) or "none")
    print("cost low", cost_low, "rec", cost_rec)


def chart(sens, R):
    W, H = 720, 330
    l, r, t, b = 58, 20, 24, 50
    xs = [s["motor_m"] for s in sens]
    x0, x1 = min(xs), max(xs)
    y0, y1 = 0.0, 4.0

    def px(v):
        return l + (v - x0) / (x1 - x0) * (W - l - r)

    def py(v):
        return t + (1 - (v - y0) / (y1 - y0)) * (H - t - b)
    o = [f'<svg viewBox="0 0 {W} {H}" class="chart" role="img" aria-label="Static stability margin at liftoff versus loaded motor mass; stays between {sens[-1]["sm"]:.2f} and {sens[0]["sm"]:.2f} calibres over 40 to 320 grams">']
    o.append(f'<rect x="{l}" y="{py(3.0):.1f}" width="{W - l - r}" height="{py(1.5) - py(3.0):.1f}" class="band"/>')
    o.append(f'<text x="{W - r - 6}" y="{py(3.0) + 14:.1f}" text-anchor="end" class="bandlab">TARGET 1.5–3.0 CAL</text>')
    for yv in (0, 1, 2, 3, 4):
        o.append(f'<line x1="{l}" x2="{W - r}" y1="{py(yv):.1f}" y2="{py(yv):.1f}" class="grid"/>')
        o.append(f'<text x="{l - 8}" y="{py(yv) + 4:.1f}" text-anchor="end" class="ax">{yv}</text>')
    for xv in range(40, 321, 40):
        o.append(f'<text x="{px(xv):.1f}" y="{H - b + 18}" text-anchor="middle" class="ax">{xv}</text>')
    o.append(f'<text x="{(l + W - r) / 2}" y="{H - 8}" text-anchor="middle" class="axt">Loaded motor mass, g (motor CG held at placeholder station)</text>')
    o.append(f'<text x="14" y="{(t + H - b) / 2}" text-anchor="middle" class="axt" transform="rotate(-90 14 {(t + H - b) / 2})">Static margin, cal</text>')
    pts = " ".join(f"{px(s['motor_m']):.1f},{py(s['sm']):.1f}" for s in sens)
    area = f"{px(x0):.1f},{py(0):.1f} " + pts + f" {px(x1):.1f},{py(0):.1f}"
    o.append(f'<polygon points="{area}" class="area"/>')
    o.append(f'<polyline points="{pts}" class="series"/>')
    for s in sens:
        hi = s["motor_m"] == int(A.MOTOR_M0)
        o.append(f'<circle cx="{px(s["motor_m"]):.1f}" cy="{py(s["sm"]):.1f}" r="{5 if hi else 3}" class="{"pt hi" if hi else "pt"}"/>')
        o.append(f'<rect x="{px(s["motor_m"]) - 12:.1f}" y="{t}" width="24" height="{H - t - b}" class="hit" '
                 f'data-m="{s["motor_m"]}" data-sm="{s["sm"]:.2f}" data-cg="{s["cg"]:.0f}" data-mass="{s["M"]:.0f}" data-x="{px(s["motor_m"]):.1f}" data-y="{py(s["sm"]):.1f}"/>')
    ph = [s for s in sens if s["motor_m"] == int(A.MOTOR_M0)][0]
    o.append(f'<text x="{px(ph["motor_m"]) + 10:.1f}" y="{py(ph["sm"]) - 10:.1f}" class="lab">placeholder {int(A.MOTOR_M0)} g → {ph["sm"]:.2f} cal</text>')
    o.append(f'<line x1="0" x2="0" y1="{t}" y2="{H - b}" class="xhair" id="xh"/>')
    o.append("</svg>")
    return "".join(o)


if __name__ == "__main__":
    main()
