// ASTRA-66 parameters -- GENERATED by build.py from analysis.py. Edit analysis.py and rebuild,
// or override here for quick CAD experiments (analysis will then be out of date).

BODY_OD          = 66.0;   // [ASSUMPTION] mm - Nominal 66 mm-class spiral kraft/phenolic body tube. MEASURE the purchased tube and update.
BODY_ID          = 64.0;   // [ASSUMPTION] mm - Measure purchased tube (3 places, 2 axes). Drives every shoulder, ring and bulkhead fit.
CPL_OD           = 63.8;   // [ASSUMPTION] mm - Matching commercial coupler. Must slip-fit BODY_ID (0.1-0.4 mm diametral clearance).
CPL_ID           = 61.0;   // [ASSUMPTION] mm - Measure purchased coupler.
TUBE_RHO         = 1.0;   // [ASSUMPTION] g/cm3 - Effective density of paper/phenolic tube. Verify by weighing a known length.
FIT_SH           = 0.3;   // [ASSUMPTION] mm - Diametral clearance, printed shoulder / ring in tube. Tune with a printed test coupon first.
NC_L             = 264.0;   // [ASSUMPTION] mm - Exposed nose length, tangent ogive, fineness 4.0 (NC_L / BODY_OD).
NC_WALL          = 1.2;   // [ASSUMPTION] mm - Printed ogive wall = 3 perimeters x 0.4 mm nozzle.
NC_SH_L          = 60.0;   // [ASSUMPTION] mm - Shoulder length ~0.9 calibre.
NC_SH_WALL       = 1.6;   // [ASSUMPTION] mm - Shoulder wall (4 perimeters); hosts radial heat-set inserts.
NC_SPLIT         = 150.0;   // [ASSUMPTION] mm - Print split station so each half fits a 250 mm Z-height printer.
NC_BH_T          = 6.0;   // [ASSUMPTION] mm - Printed nose bulkhead / ballast mount thickness.
BALLAST_ROD_L    = 80.0;   // [ASSUMPTION] mm - M6 A2 threaded rod length forward of NC-103 (rod is cut to BALLAST_ROD_L + NC_BH_T = 86).
NC_TIP_SOLID     = 8.0;   // [ASSUMPTION] mm - Solid printed tip before the internal cavity starts (CAD rev B).
NC_SPIGOT_L      = 10.0;   // [ASSUMPTION] mm - NC-101 spigot length aft of the print split (engages NC-102 socket).
NC_SPLIT_WEB     = 2.0;   // [ASSUMPTION] mm - Solid annular web closing NC-101 at the split; the spigot grows from it (CAD rev B, printable).
NC_SPIGOT_WALL   = 1.6;   // [ASSUMPTION] mm - Spigot wall thickness.
FIT_SOCKET       = 0.2;   // [ASSUMPTION] mm - Diametral clearance spigot-to-socket (I-00, slip fit +0.1/+0.3).
NC_BASE_RING     = 1.6;   // [ASSUMPTION] mm - Closing ring between ogive wall and shoulder at the nose base.
NC_BOSS_T        = 4.4;   // [ASSUMPTION] mm - Radial insert boss depth inside the shoulder (wall + boss = 6.0 >= insert + 0.5).
NC_LUG_L         = 12.0;   // [ASSUMPTION] mm - NC-103 mounting lug length (lugs end at the bulkhead forward face, CAD rev B).
NC_LUG_T         = 6.0;   // [ASSUMPTION] mm - NC-103 mounting lug radial depth.
NC_SCREW_ANG     = [90, 210, 330];   // [ASSUMPTION] deg - Angular positions of the 3 radial nose screws (I-01).
NC_LUG_ANG       = [30, 150, 270];   // [ASSUMPTION] deg - Angular positions of the 3 NC-103 lugs.
PL_L             = 250.0;   // [ASSUMPTION] mm - Payload tube length. Clear payload bay = PL_L - NC_SH_L - AV insertion - bulkheads.
CAM_LENS_HOLE    = 14.0;   // [USER-SUPPLIED] mm - Set from the chosen camera's lens barrel diameter + 1 mm.
CAM_MASS         = 35.0;   // [USER-SUPPLIED] g - Weigh the chosen camera (with its cable). 35 g is a planning placeholder.
CAM_OFF          = 36.0;   // [ASSUMPTION] mm - Camera lens-hole station aft of the nose shoulder end (STA 360).
CAM_ANG          = 270;   // [ASSUMPTION] deg - Camera / lens-cowl angular position.
CAM_TILT         = 15.0;   // [ASSUMPTION] deg - Lens axis tilted aft from radial (matches the PL-204 window).
CAM_W            = 26.0;   // [USER-SUPPLIED] mm - Camera body width (PLACEHOLDER: measure your camera). Rev B: 29 -> 26; the rev A 29 x 16 x 45 placeholder interfered with the tube wall at 15 deg tilt.
CAM_H            = 14.0;   // [USER-SUPPLIED] mm - Camera body depth along the lens axis (PLACEHOLDER; rev A 16).
CAM_LEN          = 40.0;   // [USER-SUPPLIED] mm - Camera body length (PLACEHOLDER; rev A 45). The CAD re-seats any size inside the bore; the pipeline then checks tray clearance.
CAM_LENS_L       = 5.0;   // [USER-SUPPLIED] mm - Lens barrel protrusion from the camera face (PLACEHOLDER).
HATCH_OFF        = 71.0;   // [ASSUMPTION] mm - Hatch centre station aft of the nose shoulder end (STA 395).
HATCH_ANG        = 90;   // [ASSUMPTION] deg - Hatch angular position (over the GPS).
HATCH_W          = 25.0;   // [ASSUMPTION] mm - Hatch cut-out chord width.
HATCH_L          = 40.0;   // [ASSUMPTION] mm - Hatch cut-out axial length.
HATCH_GAP        = 0.3;   // [ASSUMPTION] mm - Edge gap between hatch panel and cut-out.
HATCH_SCREW_OFF  = 17.0;   // [ASSUMPTION] mm - Hatch screws at hatch centre +/- this (on the frame ledges).
FRAME_L          = 54.0;   // [ASSUMPTION] mm - PL-206 doubler frame axial length.
FRAME_W          = 40.0;   // [ASSUMPTION] mm - PL-206 doubler frame chord width.
FRAME_T          = 2.0;   // [ASSUMPTION] mm - PL-206 frame thickness (bosses 4.5).
TRAY_L           = 90.0;   // [ASSUMPTION] mm - PL-202 overall length including the foot.
TRAY_W           = 50.0;   // [ASSUMPTION] mm - PL-202 plate width.
TRAY_T           = 2.5;   // [ASSUMPTION] mm - PL-202 plate thickness.
TRAY_FOOT_T      = 8.0;   // [ASSUMPTION] mm - PL-202 foot thickness (bears on AV-303).
TRAY_HOLE_X      = 7.0;   // [ASSUMPTION] mm - Tray screw holes at x = +/- this (CAD rev B: clears tee-nut flanges).
TRAY_HOLE_Y      = -14.0;   // [ASSUMPTION] mm - Tray screw holes at y = this (below the sled plane).
AV_CPL_L         = 170.0;   // [ASSUMPTION] mm - Coupler length = 70 insertion + 30 switch band + 70 insertion.
AV_INS           = 70.0;   // [ASSUMPTION] mm - Coupler insertion each side (~1.1 calibre; >= 1 calibre is the usual rule of thumb).
AV_BAND_L        = 30.0;   // [ASSUMPTION] mm - Switch band length (exposed airframe ring).
AV_BH_T          = 6.0;   // [ASSUMPTION] mm - Each bulkhead disc thickness (birch ply); 2 discs per bulkhead.
AV_ROD_SP        = 40.0;   // [ASSUMPTION] mm - Threaded-rod spacing (M4) in the sled plane.
SLED_L           = 140.0;   // [ASSUMPTION] mm - Electronics sled length.
SLED_W           = 52.0;   // [ASSUMPTION] mm - Electronics sled width (fits CPL_ID with rod sleeves).
SLED_T           = 3.0;   // [ASSUMPTION] mm - Sled thickness (PETG, 100% infill between rod sleeves).
SLED_FWD_GAP     = 7.0;   // [ASSUMPTION] mm - Gap AV-303 to sled = forward AV-312 spacer length.
GASKET_T         = 0.5;   // [ASSUMPTION] mm - AV-309 face gasket compressed thickness (1.5 mm foam free). CAD rev B: moves AV-304 outer disc aft by this.
SW_ANG           = 90;   // [ASSUMPTION] deg - Arming-switch access angle.
SW_HOLE_D        = 8.0;   // [ASSUMPTION] mm - Switch access hole through AV-302 + AV-301.
SW_TOWER_H       = 20.0;   // [USER-SUPPLIED] mm - Switch tower height above sled; set so the switch actuator sits ~1 mm below CPL_ID.
STATIC_PORT_D    = 2.0;   // [ASSUMPTION] mm - 4 static ports at 45/135/225/315 deg (size per sensor maker guidance).
HARNESS_D        = 8.0;   // [ASSUMPTION] mm - Harness hole through AV-303 (grommet).
HARNESS_Y        = 14.0;   // [ASSUMPTION] mm - Harness hole centre offset toward the switch side (+Y).
BAT_L            = 55.0;   // [USER-SUPPLIED] mm - Battery length (PLACEHOLDER: set from purchased cell).
BAT_W            = 28.0;   // [USER-SUPPLIED] mm - Battery width (PLACEHOLDER; max 28.8 to clear the rod sleeves).
BAT_H            = 9.0;   // [USER-SUPPLIED] mm - Battery thickness (PLACEHOLDER).
ROD_L            = 190.0;   // [ASSUMPTION] mm - AV-305 M4 rod length (fwd bulkhead face to 1.7 mm past the aft nut).
BO_L             = 600.0;   // [ASSUMPTION] mm - Booster tube length (recovery bay + fin can).
MMT_OD           = 31.0;   // [ASSUMPTION] mm - 29 mm-class motor mount tube OD. Measure purchased tube.
MMT_ID           = 29.0;   // [COMMERCIAL SPEC] mm - PLACEHOLDER ONLY (MMT bore for the motor casing). Replace via simulation/motor_config.json with the selected certified product's published data.
MMT_L            = 260.0;   // [COMMERCIAL SPEC] mm - PLACEHOLDER ONLY (MMT length >= longest motor + retainer requirement). Replace via simulation/motor_config.json with the selected certified product's published data.
MMT_AFT_EXT      = 10.0;   // [COMMERCIAL SPEC] mm - PLACEHOLDER ONLY (MMT protrusion aft of airframe for the retainer). Replace via simulation/motor_config.json with the selected certified product's published data.
CR_T             = 6.0;   // [ASSUMPTION] mm - Forward centering ring thickness (birch ply, recovery-load anchor ring).
CORE_RING_T      = 8.0;   // [ASSUMPTION] mm - Fin-can core ring thickness (ASA print).
CORE_RAIL_T      = 1.6;   // [ASSUMPTION] mm - Fin guide rail thickness.
LOCK_T           = 6.0;   // [ASSUMPTION] mm - Aft fin lock ring thickness (birch ply: heat tolerant near motor).
RET_CLEAR_D      = 40.0;   // [COMMERCIAL SPEC] mm - Lock-ring bore = retainer body OD + 1 mm. PLACEHOLDER ONLY (retainer body OD). Replace via simulation/motor_config.json with the selected certified product's published data.
FIN_N            = 4;   // [ASSUMPTION] - - Fin count. 4 fins -> symmetric layout for rail buttons, camera and slide-in guides.
FIN_CR           = 150.0;   // [ASSUMPTION] mm - Root chord (exposed).
FIN_CT           = 60.0;   // [ASSUMPTION] mm - Tip chord.
FIN_S            = 60.0;   // [ASSUMPTION] mm - Semi-span (exposed, from body surface). Selected by trade study for 2-3 cal margin.
FIN_XR           = 70.0;   // [ASSUMPTION] mm - Leading-edge sweep length (root LE to tip LE, parallel to axis). Tip TE stays 20 mm forward of the tail.
FIN_T            = 3.0;   // [ASSUMPTION] mm - Fin thickness: 3 mm aircraft birch ply (baseline) or 3.2 mm G10 (upgrade, heavier).
FIN_TAB_FWD      = 10.0;   // [ASSUMPTION] mm - Tab starts this far aft of root LE.
FIN_SLOT_CLR     = 0.3;   // [ASSUMPTION] mm - Tube slot width = FIN_T + FIN_SLOT_CLR.
FIN_GUIDE_CLR    = 0.2;   // [ASSUMPTION] mm - Printed guide slot width = FIN_T + FIN_GUIDE_CLR.
FIN_TAB_CLR      = 0.2;   // [ASSUMPTION] mm - Radial clearance between fin tab root and the BO-403 tab floor.
LOCK_SCREW_R     = 26.0;   // [ASSUMPTION] mm - Pitch radius of the 4 lock-ring screws (45/135/225/315 deg).
RB_FWD_OFF       = 9.0;   // [ASSUMPTION] mm - Forward rail button this far forward of the MMT forward end (on BO-409).
RB_AFT_OFF       = 29.0;   // [ASSUMPTION] mm - Aft rail button this far forward of the tail (on BO-403 boss).
RB_ANG           = 45;   // [ASSUMPTION] deg - Rail-button line, midway between fins 1 and 2.
KEVLAR_NOTCH_ANG = 225;   // [ASSUMPTION] deg - Aramid leader notch in BO-404 (opposite the rail line).
INS_M3_D         = 4.0;   // [ASSUMPTION] mm - Hole for M3 brass heat-set insert (use the insert maker's value).
INS_M3_L         = 5.0;   // [ASSUMPTION] mm - M3 insert length (insert maker).
INS_M25_D        = 3.6;   // [ASSUMPTION] mm - Hole for M2.5 heat-set insert (insert maker).
INS_M25_L        = 4.0;   // [ASSUMPTION] mm - M2.5 insert length (insert maker).
INS_M4_D         = 5.6;   // [ASSUMPTION] mm - Hole for M4 heat-set insert in printed bosses (insert maker).
INS_M4_L         = 6.0;   // [ASSUMPTION] mm - M4 insert length (insert maker).
CLR_M25          = 2.9;   // [COMMERCIAL SPEC] mm - ISO 273 medium clearance hole, M2.5.
CLR_M3           = 3.4;   // [COMMERCIAL SPEC] mm - ISO 273 medium clearance hole, M3.
CLR_M4           = 4.5;   // [COMMERCIAL SPEC] mm - ISO 273 medium clearance hole, M4.
CLR_M6           = 6.5;   // [ASSUMPTION] mm - Close clearance for the M6 eyebolt / ballast rod.
TNUT_BARREL_D    = 5.5;   // [ASSUMPTION] mm - M4 tee-nut barrel hole (confirm with purchased tee-nut).
TNUT_FLANGE_D    = 15.0;   // [ASSUMPTION] mm - M4 tee-nut flange diameter (confirm; used for clearance checks).
TNUT_FLANGE_T    = 1.5;   // [ASSUMPTION] mm - M4 tee-nut flange thickness (confirm).
NUT_M4_H         = 5.0;   // [COMMERCIAL SPEC] mm - DIN 985 M4 nylock nut height (verify against purchased part).
WASHER_M4_T      = 0.8;   // [COMMERCIAL SPEC] mm - ISO 7089 M4 washer thickness.
SHCS_M3_DK       = 5.5;   // [COMMERCIAL SPEC] mm - ISO 4762 M3 socket-head diameter (tool-access checks).
RB_ENV_D         = 12.0;   // [COMMERCIAL SPEC] mm - Rail-button ENVELOPE placeholder diameter; real size from button maker.
RB_ENV_H         = 9.0;   // [COMMERCIAL SPEC] mm - Rail-button ENVELOPE placeholder standoff; real size from button maker.
EYE_ENV_D        = 24.0;   // [COMMERCIAL SPEC] mm - M6 eyebolt ENVELOPE placeholder (eye OD); from eyebolt maker.
EYE_ENV_L        = 36.0;   // [COMMERCIAL SPEC] mm - M6 eyebolt ENVELOPE placeholder length aft of AV-304.
RET_ENV_L        = 22.0;   // [COMMERCIAL SPEC] mm - PLACEHOLDER ONLY (retainer length aft of airframe). Replace via simulation/motor_config.json with the selected certified product's published data.
FN               = 96;   // [ASSUMPTION] - - OpenSCAD facets per full circle (CAD resolution only).
PETG_RHO         = 1.27;   // [ASSUMPTION] g/cm3 - Typical PETG filament density (check spool datasheet).
ASA_RHO          = 1.07;   // [ASSUMPTION] g/cm3 - Typical ASA filament density (check spool datasheet).
PLY_RHO          = 0.68;   // [ASSUMPTION] g/cm3 - Aircraft birch plywood, typical. Weigh your sheet.
STEEL_RHO        = 7.9;   // [ASSUMPTION] g/cm3 - Stainless steel A2.
MOTOR_L          = 125.0;   // [COMMERCIAL SPEC] mm - PLACEHOLDER ONLY (motor length). Replace via simulation/motor_config.json with the selected certified product's published data.
MOTOR_M0         = 110.0;   // [COMMERCIAL SPEC] g - PLACEHOLDER ONLY (loaded motor mass). Replace via simulation/motor_config.json with the selected certified product's published data.
MOTOR_MB         = 55.0;   // [COMMERCIAL SPEC] g - PLACEHOLDER ONLY (burnout motor mass). Replace via simulation/motor_config.json with the selected certified product's published data.
RET_MASS         = 25.0;   // [COMMERCIAL SPEC] g - PLACEHOLDER ONLY (retainer mass). Replace via simulation/motor_config.json with the selected certified product's published data.
V_DESC           = 5.0;   // [ASSUMPTION] m/s - Target descent rate under main parachute.
CHUTE_D          = 1067.0;   // [ASSUMPTION] mm - Selected nominal parachute diameter (42 in class) from the descent-rate calculation.
CHUTE_CD         = 0.8;   // [ASSUMPTION] - - Parachute drag coefficient on nominal area. Replace with the chute manufacturer's figure if published.
RHO_AIR          = 1.225;   // [ASSUMPTION] kg/m3 - ISA sea level. Use site altitude/temperature in the simulator (USER).
SHOCK_K          = 1.8;   // [ASSUMPTION] - - Opening-shock amplification over steady drag (conservative planning value).
N_AX             = 15.0;   // [ASSUMPTION] g - Design axial load factor. REPLACE with 1.5 x simulated peak acceleration of the chosen motor.
V_MAX            = 90.0;   // [ASSUMPTION] m/s - Design velocity limit for this airframe (printed nose, kraft tubes, ply fins).
ALPHA_GUST       = 10.0;   // [ASSUMPTION] deg - Angle of attack for fin side-load check (rail exit in cross-wind).
TAU_BOND         = 1.0;   // [ASSUMPTION] MPa - Allowable shear on epoxy-to-paper tube bonds (paper delamination governs; very conservative).
PLY_SIG          = 40.0;   // [ASSUMPTION] MPa - Allowable bending stress, birch ply (conservative vs typical published values).
PLY_G            = 0.6;   // [ASSUMPTION] GPa - In-plane shear modulus, 3 mm birch ply (for flutter screening only).
TUBE_E           = 3.0;   // [ASSUMPTION] GPa - Axial modulus of kraft/phenolic tube (vibration order-of-magnitude only).
A2_70_PROOF      = 450.0;   // [COMMERCIAL SPEC] MPa - ISO 3506-1 property class A2-70 minimum 0.2% proof stress.
M4_AS            = 8.78;   // [COMMERCIAL SPEC] mm2 - ISO 898 / ISO 724 tensile stress area, M4 coarse.
RAIL_L           = 1.0;   // [USER-SUPPLIED] m - Usable rail length at YOUR range (planning value 1.0 m).
